### ISSUE TITLE
User can view homepage

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/ajax-project#1]
## 💰 Motivation

Users can navigate throughout the app.

## 📐 Plan

Create a page that users can come back to to help navigate through the app.

## 🖼️ Wireframe

![user can view the homepage](https://user-images.githubusercontent.com/70028619/98714875-448d7d80-233e-11eb-8180-22226d6dfa20.png)

## ✅ Task List
- [x] Create a header for the app.
- [x] Create a body for the app.
- [x] Create a footer for navigation throughout the app.
