### ISSUE TITLE
User can find random taco recipes

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/ajax-project#2]
## 💰 Motivation

Users can get random recipes for tacos.

## 📐 Plan

Create a page where users can cycle through random recipes and save the ones they like.

## 🖼️ Wireframe

![User can find random taco recipes](https://user-images.githubusercontent.com/70028619/98750465-dfa04a80-2372-11eb-9b21-4839c7e670a3.png)

## ✅ Task List
- [x] Using HTML/CSS create window for random taco recipes
- [x] Using JavaScript create random recipe generator with API from Taco Fancy (https://github.com/evz/tacofancy-api)
- [x] Create a button where users can cycle through recipes
- [x] Create a button for users to save recipes.
