### ISSUE TITLE
User can find and save random beer to go with tacos

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/ajax-project#3]
## 💰 Motivation

Users can get random recipes for tacos.

## 📐 Plan

Create a page where users can cycle through random recipes and save the ones they like.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/70028619/98883006-68d28280-2442-11eb-85a2-5dfa0871b965.png)

## ✅ Task List
- [x] Using HTML/CSS create window for random beer recipes
- [x] Using JavaScript create random beer generator with API from punkAPI (https://punkapi.com/documentation/v2)
- [x] Create a button where users can cycle through beers
- [x] Create a button for users to save beers.
- [x] Set up local storage.
