### ISSUE TITLE
User can find random tacos and beer combos.

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/ajax-project#4]
## 💰 Motivation

Users can get random recipes for tacos and beers that compliment the tacos.

## 📐 Plan

Create a page where users can cycle through random recipes and beers, and save the ones they like.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/70028619/98982017-93205080-24d3-11eb-8316-00e59278322d.png)

## ✅ Task List
- [x] Using HTML/CSS create window for random beers.
- [x] Using JavaScript create random beer generator with API from punkAPI (https://punkapi.com/documentation/v2)
- [x] Create a button where users can cycle through beers
- [x] Create a button for users to save beers.
- [x] Using HTML/CSS create window for random taco recipes.
- [x] Using JavaScript create random taco generator with API from Taco Fancy (https://github.com/evz/tacofancy-api)
- [x] Create a button where users can cycle through recipes
- [x] Create a button for users to save recipes.
- [x] Create button for users to cycle combos.
- [x] create button for users to save combos.
