### ISSUE TITLE
User can view saved items

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/ajax-project#5]
## 💰 Motivation

Users can view items they have saved

## 📐 Plan

Create a page where users can view the items they have saved.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/70028619/99016217-7a339180-250b-11eb-870e-a5dca1238099.png)

## ✅ Task List
- [x] Using HTML/CSS create a window where users can decide which items they want to view.
- [x] Add navigation to different views
- [x] Using HTML/CSS/JavaScript create a window that shows the items the user saved in order from newest to oldest.
- [x] Using HTML/CSS create window for user to view selected saved item.
